spring:
  application:
    name: switchyard-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SWITCHYARD_OIDC_ISSUER_URI:http://localhost:9000}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: io.jonathanlee.switchyard_api.mappers.typehandlers

spring.cache:
  type: redis
  redis:
    time-to-live: 8h
